# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 391)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setObjectName("form_layout")
        self.label = QtWidgets.QLabel(self.central_widget)
        self.label.setObjectName("label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.central_widget)
        self.label_2.setObjectName("label_2")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.central_widget)
        self.label_3.setObjectName("label_3")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.central_widget)
        self.label_4.setObjectName("label_4")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.central_widget)
        self.label_5.setObjectName("label_5")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.central_widget)
        self.label_6.setObjectName("label_6")
        self.form_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.name = QtWidgets.QLineEdit(self.central_widget)
        self.name.setInputMask("")
        self.name.setText("")
        self.name.setObjectName("name")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.degree_roasting = QtWidgets.QSpinBox(self.central_widget)
        self.degree_roasting.setMinimum(1)
        self.degree_roasting.setMaximum(5)
        self.degree_roasting.setObjectName("degree_roasting")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.degree_roasting)
        self.price = QtWidgets.QDoubleSpinBox(self.central_widget)
        self.price.setMinimum(0.0)
        self.price.setMaximum(9999999999999.99)
        self.price.setObjectName("price")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.price)
        self.packing_volume = QtWidgets.QSpinBox(self.central_widget)
        self.packing_volume.setMinimum(1)
        self.packing_volume.setMaximum(999999999)
        self.packing_volume.setSingleStep(1)
        self.packing_volume.setObjectName("packing_volume")
        self.form_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.packing_volume)
        self.is_ground = QtWidgets.QCheckBox(self.central_widget)
        self.is_ground.setObjectName("is_ground")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.is_ground)
        self.description = QtWidgets.QLineEdit(self.central_widget)
        self.description.setObjectName("description")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.description)
        self.verticalLayout.addLayout(self.form_layout)
        self.ok_button = QtWidgets.QPushButton(self.central_widget)
        self.ok_button.setObjectName("ok_button")
        self.verticalLayout.addWidget(self.ok_button)
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Добавить или изменить кофе"))
        self.label.setText(_translate("MainWindow", "Название сорта:"))
        self.label_2.setText(_translate("MainWindow", "Степень прожарки:"))
        self.label_3.setText(_translate("MainWindow", "Молотый:"))
        self.label_4.setText(_translate("MainWindow", "Описание вкуса:"))
        self.label_5.setText(_translate("MainWindow", "Цена:"))
        self.label_6.setText(_translate("MainWindow", "Объём упаковки:"))
        self.name.setPlaceholderText(_translate("MainWindow", "Название сорта"))
        self.is_ground.setText(_translate("MainWindow", "Нет"))
        self.description.setPlaceholderText(_translate("MainWindow", "Описание"))
        self.ok_button.setText(_translate("MainWindow", "Создать"))
